# Generated by Django 3.2.2 on 2022-04-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('care_guide', models.CharField(blank=True, default='', max_length=100)),
                ('common_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sci_name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=5)),
            ],
        ),
    ]
